#Master playbook for app deployment
---
- include: common.yml
- name: graph_gallery playbook  
  hosts: all 
  user: vagrant
  sudo: yes
  roles:
    - {role: github, pull_repo: true, repo: graph_gallery}
    - {role: nginx, set_vhost: true, apps: [{name: "graph_gallery", https: false, port: 80, hostname: "localhost", root: "/home/web/graph_gallery"}]}
  tasks:
    - name:  Watch coffee dir for changes, and recompile 
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - htop
        - ack-grep
        - tree
        - tmux
