---
# tasks file for user

- group: name={{item}} state=present
  with_items:
    - www-data
  tags: configure

- name: Create user     
  user: name={{user}} groups=www-data append=yes
  tags: configure

- name: ensure .ssh dir exist
  file: path=/home/{{ user }}/.ssh state=directory
- name: Copy dotfiles
  copy: src=~/{{ item }} dest=/home/{{ user }}/{{ item }}
  with_items:
    - .gitconfig
    - .ssh/id_rsa
    - .ssh/id_rsa.pub

