---
# tasks file for user

- group: name={{item}} state=present
  with_items:
    - www-data
  tags: configure

- name: Create user     
  user: name={{user}}	generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa groups=www-data append=yes
  tags: configure

