#!/bin/sh


#chkconfig: 35 99 99
#description: popcorn 
. /etc/rc.d/init.d/functions

USER="root"

DAEMON="/usr/local/bin/geddy"
PARAMS="-g /usr/share/nginx/popcorn -p 2000"

LOCK_FILE="/var/lock/subsys/popcorn"

do_start()
{
  if [ ! -f "$LOCK_FILE" ] ; then
    echo -n $"Starting $SERVER: "
      runuser -l "$USER" -c "$DAEMON $PARAMS &" && echo_success || echo_failure
      RETVAL=$?
      echo
      [ $RETVAL -eq 0 ] && touch $LOCK_FILE
  else
    echo "$SERVER is locked."
      RETVAL=1
      fi
}
do_stop()
{
  echo -n $"Stopping $SERVER: "
    pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
    kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
start)
do_start
;;
stop)
do_stop
;;
restart)
do_stop
do_start
;;
*)
echo "Usage: $0 {start|stop|restart}"
RETVAL=1
esac

exit $RETVAL
