---
# tasks file for vim
- name: Install vim and dependencies  
  #pacman: name={{item}} state=latest update_cache=yes
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - vim
    - curl

- name: Clone vundle repo
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/{{user}}/.vim/bundle/Vundle.vim

- name: Ensure exsistance of conf folder in home directory
  file: path=/home/{{user}}/conf/ state=directory owner={{user}} recurse=yes

- name: Ensure exsistance  and writ of .vim folder in home directory
  file: path=/home/{{user}}/.vim state=directory owner={{user}} recurse=yes

- name: deploy .vimrc
  template: src=vimrc.j2 dest=/home/{{user}}/conf/vimrc owner={{user}} backup=yes

- name: symlink vimrc
  file: path=/home/{{user}}/.vimrc src=/home/{{user}}/conf/vimrc state=link owner={{user}} 

- name: install plugins
  shell: vim +PluginInstall +qall

